/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iteye_weimingtom_wce_clipboard_ClipboardJNI */

#ifndef _Included_com_iteye_weimingtom_wce_clipboard_ClipboardJNI
#define _Included_com_iteye_weimingtom_wce_clipboard_ClipboardJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iteye_weimingtom_wce_clipboard_ClipboardJNI
 * Method:    setClipboardViewer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_iteye_weimingtom_wce_clipboard_ClipboardJNI_setClipboardViewer
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
